name: cornerstonecoimbatore
favicon: null
layout_spectrum: 0.8275745024438947
typography_spectrum: 0.14142899820581079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.002467074664309621
  lightness: 0.33259328827261925
  saturation: 0.42829784471541643
  rhythmicContrast: 0.046449481043964624
purpose: []
